### ISSUE TITLE
Complete the consumer part with pause and unpause

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-amqp-dotnet-client#37]
### Is your feature request related to a problem? Please describe.

Implement `pause` and `unpause` for consumer part 

### Describe the solution you'd like

I tried to implement it, but it seems that the [AMQP lite client](https://github.com/Azure/amqpnetlite) does not expose these features.  See like Java client: https://rabbitmq.github.io/rabbitmq-amqp-java-client/snapshot/htmlsingle/#graceful-shutdown

**Comment by lukebakken** [comment]
Notes:
* https://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#doc-session-flow-control

**Comment by acogoluegnes** [comment]
See the example in the spec: https://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#doc-idp429232.

It consists in sending a `flow` performative with credits = 0 (no more messages) and echo = true (send the flow state back). So when the client receives the flow state from the server, it knows the server got the request and should not send messages anymore. The client can still have messages in its own buffer or messages being processed by the application, but at least they know the link has quiesced.

This can be used to:
 * gracefully closing a consumer (stopping the link, then detaching it)
 * pausing a consumer (you unpause it by giving more credits)

**Comment by lukebakken** [comment]
Thanks @acogoluegnes. I also found where this is done in the Java client code.
