### ISSUE TITLE
Semantics of IConsumer.BuildAsync() start consume.

### ISSUE THREAD

**Issue by luizcarlosfaria** [rabbitmq/rabbitmq-amqp-dotnet-client#59]
### Is your feature request related to a problem? Please describe.

Method BuildAsync of interface IConsumer is constructing AmqpConsumer and starting it.

### Describe the solution you'd like

Maybe change the name of the method Semantics of IConsumer.BuildAsync() start consume to 

- StartConsumeAsync()
- StartAsync()
- BuildAndStartAsync()

any name that describes that consumer is starting and not only builded.

### Describe alternatives you've considered

- Change the name of the method, maintaining the implementation.

- Split Build in Build() and Start() methods in a correct flow

**Comment by Gsantomaggio** [comment]
Thank you @luizcarlosfaria 
Yes, it makes sense. Maybe `BuildAndStartAsync` is the correct one. 
@lukebakken ?
